"""add graph tables for graphrag phase1

Revision ID: 5a3e68f03094
Revises: 60fa8925e61b
Create Date: 2026-05-07 22:34:58.689725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5a3e68f03094'
down_revision: Union[str, Sequence[str], None] = '60fa8925e61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('entity_text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('vector_external_id', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('extraction_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('extraction_prompt_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.create_index('ix_graph_entities_collection_id', ['collection_id'], unique=False)
        batch_op.create_index('ix_graph_entities_collection_id_entity_text', ['collection_id', 'entity_text'], unique=False)
        batch_op.create_index('ix_graph_entities_document_id', ['document_id'], unique=False)

    op.create_table('graph_extraction_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_extraction_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_graph_extraction_jobs_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_graph_extraction_jobs_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('extraction_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_graph_edges_document_id', ['document_id'], unique=False)
        batch_op.create_index('ix_graph_edges_source_entity_id', ['source_entity_id'], unique=False)
        batch_op.create_index('ix_graph_edges_target_entity_id', ['target_entity_id'], unique=False)

    # NOTE: autogenerate also detected pg_vectors/api_keys/collections diffs but
    # those are SQLite schema reflection artefacts (FK emulation, constraint naming).
    # They are intentionally excluded — only the three graph tables are created here.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_edges_target_entity_id')
        batch_op.drop_index('ix_graph_edges_source_entity_id')
        batch_op.drop_index('ix_graph_edges_document_id')

    op.drop_table('graph_edges')
    with op.batch_alter_table('graph_extraction_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_extraction_jobs_status_created_at')
        batch_op.drop_index('ix_graph_extraction_jobs_document_id')

    op.drop_table('graph_extraction_jobs')
    with op.batch_alter_table('graph_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_graph_entities_document_id')
        batch_op.drop_index('ix_graph_entities_collection_id_entity_text')
        batch_op.drop_index('ix_graph_entities_collection_id')

    op.drop_table('graph_entities')
    # ### end Alembic commands ###
