"""initial schema with collections and blob vectors

Revision ID: de4f446e96e3
Revises: 
Create Date: 2026-04-07 09:40:47.826306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4f446e96e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=True)

    op.create_table('vectors',
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('internal_id'),
    sa.UniqueConstraint('collection_id', 'external_id', name='uq_collection_external_id')
    )
    with op.batch_alter_table('vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vectors_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vectors_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vectors_internal_id'), ['internal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vectors_internal_id'))
        batch_op.drop_index(batch_op.f('ix_vectors_external_id'))
        batch_op.drop_index(batch_op.f('ix_vectors_collection_id'))

    op.drop_table('vectors')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_name'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))

    op.drop_table('collections')
    # ### end Alembic commands ###
